kind: Deployment
apiVersion: apps/v1
metadata:
  name: docling-serve-two
  namespace: ckoep-docling-serve
  labels:
    app: docling-serve
    component: docling-serve-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docling-serve
      component: docling-serve-api
  template:
    metadata:
      labels:
        app: docling-serve
        component: docling-serve-api
    spec:
      containers:
        - name: api
          image: ghcr.io/docling-project/docling-serve-cu124
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          env:
            - name: DOCLING_SERVE_ENABLE_UI
              value: 'true'
          resources:
            limits:
              cpu: '1'
              memory: 4Gi
            requests:
              cpu: 250m
              memory: 1Gi
      restartPolicy: Always
